### 00. PyTorch Fundementals

Resource Notebook: https://www.learnpytorch.io/

In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2+cu118


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensore()` = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], 
                        [3,6,9], 
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7508, 0.6584, 0.9218, 0.2190],
        [0.2927, 0.3990, 0.1915, 0.1346],
        [0.9412, 0.4811, 0.6977, 0.8662]])

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width, color channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones


In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones([3,4])
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensor-like

In [24]:
# Use torch.arange()
one_to_ten = torch.arange(start = 0, end = 11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors like name and _like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes

** Note: ** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)


In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what datatype is the tensor (eg. float32, float16)
                               device=None, # what device is your tensor stored on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatyple from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`

In [32]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2986, 0.5865, 0.4565, 0.2943],
        [0.9861, 0.1867, 0.1604, 0.5767],
        [0.6278, 0.2370, 0.1344, 0.2703]])

In [33]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.2986, 0.5865, 0.4565, 0.2943],
        [0.9861, 0.1867, 0.1604, 0.5767],
        [0.6278, 0.2370, 0.1344, 0.2703]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplcation i  neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information about matraces - https://www.mathsisfun.com/algebra/matrix-multiplying.html


There are two rules that performing matrix multiplication needs to satisfy
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [39]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

tensor([[1.6925, 1.2426, 1.7270],
        [2.7510, 1.8997, 2.9683],
        [1.6760, 1.0306, 1.6676]])

In [40]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [41]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [43]:
%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]

print(value)

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 4.53 µs
tensor(14)


In [44]:
%time
torch.matmul(tensor, tensor)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 7.63 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [45]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                        [3,4],
                         [5,6]] )

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

# torch.mm(tensor_A, tensor_B)  torch.mm is the same as torch.matmul (it is an alias)

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [46]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [47]:
tensor_B.T, " ", tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 ' ',
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [48]:

tensor_B.T.shape, " ", tensor_B.shape

(torch.Size([2, 3]), ' ', torch.Size([3, 2]))

In [49]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shapes: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shapes: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregations)

In [50]:
# Create a tensor
x = torch.arange(0, 100, 10, dtype=torch.float16)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [51]:
torch.min(x), x.min()

(tensor(0., dtype=torch.float16), tensor(0., dtype=torch.float16))

In [52]:
torch.max(x), x.max()

(tensor(90., dtype=torch.float16), tensor(90., dtype=torch.float16))

In [53]:
# Find the mean - note the torch.mean() function requires a tensor of float
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [54]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450., dtype=torch.float16), tensor(450., dtype=torch.float16))

### Finding the positional min and max

In [55]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [56]:
# Find the position in tensor that has the minumum vakue with argmin() -> returns index position of tensor where index occurs
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [57]:
x[0]

tensor(0., dtype=torch.float16)

In [58]:
# Find the position in the tensor that has the maximum value with argmax()
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

### Reshaping, stacking, sqeexing and unsqueexing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certian way


In [59]:
# Lets create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [60]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# Change the view - persists changes to original object
z = x.view(1, 9)
z.shape

torch.Size([1, 9])

In [62]:
# Changing z changes x (because a view of tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [63]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [64]:
# torch.squeeze() - removes all single dimensions froma  target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")


x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [65]:
# torch.unsqueeze() - add a single dimensions to a target tensor at a specific dim (dimension)

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueez
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}") # [color_channels, height, width]

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [66]:
# torch.permute() - rearranges the dimensions of a target tensor in a specific order

x_original = torch.rand(size = (224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to reaarange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [67]:
# Permute is a view -  persists changes to original object
x_original[0, 0, 0] = 755656
x_original[0, 0, 0] = x_permuted[0, 0, 0]


### Indexing (selecting data from a tensor)

Indexing with PyTorch is similar to indexing with NumPy

In [68]:
# Create a tensor
x = torch.arange(1., 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [69]:
# Let's index on our new tensor
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [70]:
# Let's index on the middle bracket
x[0][0] 
x[0, 0] # same

tensor([1., 2., 3.])

In [71]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]
x[0, 1, 1]

tensor(5.)

In [72]:
# You can also use ":" to select "all" of the target dimension
x[:, 0]

tensor([[1., 2., 3.]])

In [73]:
# Get all values of 0th and 1st dimensions but only index 1 of the 2nd dimension

x[:, :, 1]

tensor([[2., 5., 8.]])

In [74]:
# Get all values of the 0 dimensions but only 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5.])

In [75]:
# Get index 0 of 0th and 1st dimensions and all values of 2nd dimension
x[0, 0, :]

tensor([1., 2., 3.])

In [76]:
# Index on x to return 9
print(x[0,2,2])

# Index on x to return 3, 6, 9
print(x[0, :, 2])

tensor(9.)
tensor([3., 6., 9.])


### PyTorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library.

And because of this PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy `torch.Tensor.numpy()`

In [77]:
# Numpy array tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [78]:
# Change the value of array, what will this do to `tensor`
array = array  + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [79]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [80]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibity (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> agian -> agian -> agian...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavor" the randomness

In [81]:
# Creat two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4606, 0.8369, 0.0710, 0.5710],
        [0.1635, 0.3039, 0.8296, 0.0494],
        [0.0252, 0.1748, 0.9236, 0.3922]])
tensor([[0.1254, 0.4964, 0.6985, 0.7007],
        [0.8983, 0.2444, 0.3099, 0.1996],
        [0.6650, 0.9188, 0.2954, 0.9081]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [92]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra Resources for reproducibility
https://pytorch.org/docs/stable/notes/randomness.html

### Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU. (options to upgrade as well)

2. Use your own GPU - takes a little but of setup and requires the investment of purchasing a GPU, there's lots of option (lookup best options)

3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of set up

### Check for GPU access with PyTorch

Device Agnostic code (to run on GPU or CPU) - https://pytorch.org/docs/stable/notes/cuda.html

In [93]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

False

In [94]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [95]:
# Count number of devices
torch.cuda.device_count()

0

### Putting tensors (and models) on the GPU

The reason we want our tensors/mdels on the GPU is because using a GPU results in faster computation

In [97]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [98]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### Moving tensors back to the CPU


In [100]:
tensor_on_gpu.numpy() # would error if tensor is on a GPU

array([1, 2, 3])

In [101]:
# To fix the GPU tensor with NumPy issue, we ca first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])